name: Update Snake Animation

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  push:
    paths:
      - 'README.md'

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        run: |
          curl -o snake.svg https://raw.githubusercontent.com/Platane/snk/output/github-contribution-grid-snake.svg

      - name: Commit and Push the Updated README
        run: |
          git config user.name 'Priyam12345-cloud'
          git config user.email 'rajpriyam27@gmail.com'
          git add README.md
          git commit -m 'Update README with new snake animation'
          git push origin main

